title: "Introvert’s Dating Guide 💬"
email: "you@example.com"
description: "Tips for introverted men navigating dating"
baseurl: "" # leave blank if using username.github.io
url: "https://yourdomain.com"

theme: jekyll-architect-theme
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog

markdown: kramdown
