title: My Sample Site
description: A simple GitHub Pages site using the Cayman theme.
theme: jekyll-theme-cayman  # This activates the full header and layout
plugins:
  - jekyll-feed  # Optional: Adds RSS feed

# Navigation links for the header (theme auto-renders as top nav bar)
header_pages:
  - index.md
  - about.md

# Optional: Custom footer or other settings
footer_links:
  - title: GitHub
    url: https://github.com/your-username/your-repo
